name: Fetch Stock Data and Deploy

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 */8 * * *" # Runs every 8 hours

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Fetch latest data from gh-pages
              run: |
                  git fetch origin gh-pages:gh-pages
                  git checkout gh-pages -- last_updated.json ticker_info.json sec_info.json valid_tickers.json errors.json all_usd_tickers.csv
                  git checkout main

            - name: Fetch stock data
              run: node stock-data-fetcher.mjs

            - name: Replace Google Analytics ID
              run: |
                  sed -i 's/GOOGLE_ANALYTICS_ID/${{ secrets.GOOGLE_ANALYTICS_ID }}/g' index.html

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: .
                  publish_branch: gh-pages
                  force_orphan: true
