name: Fetch Stock Data and Deploy

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 */8 * * *" # Runs every 8 hours

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Fetch stock data
              run: node stock-data-fetcher.mjs

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: .
                  publish_branch: gh-pages
                  force_orphan: true
